[package]
name = "combine_image"
version = "0.1.0"
authors = ["zsytssk <zsytssk@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21.0"
rect_packer = "0.2.1"
lazy_static = "1.3.0"

[lib]
name = "lib"
path = "src/lib.rs"