[package]
name = "combine_image"
version = "0.1.0"
authors = ["zsytssk <zsytssk@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21.2"
rect_packer = "0.2.1"
raster = "0.2.0"
threadpool = "1.7.1"
once_cell = "0.2.1"

[lib]
name = "lib"
path = "src/lib.rs"